[build]
  base = "frontend"
  publish = "build"
  command = "npm install && npm run build"

[dev]
  command = "npm start"
  port = 3000

[build.environment]
  NODE_VERSION = "18"
  REACT_APP_API_URL = "https://campuskart-backend.herokuapp.com"  # This will be updated when we deploy the backend

[context.production]
  command = "npm install && npm run build"

[context.production.environment]
  NODE_VERSION = "18"
  REACT_APP_API_URL = "https://campuskart-backend.herokuapp.com"
