[nixpacks]
build = "cd backend && npm install"
run = "cd backend && npm start"

[env]
PORT = "5000"
MONGODB_URI = "mongodb+srv://your-username:your-password@your-cluster.mongodb.net/campuskart?retryWrites=true&w=majority"
JWT_SECRET = "your-secret-key"
