// Library Books Seed Data
const libraryBooks = [
  // Fiction Books (20 books)
  {
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    isbn: "9780061120084",
    category: "fiction",
    description: "The story of racial injustice and the loss of innocence in the American South during the Great Depression.",
    location: "Section A, Shelf 1",
    totalCopies: 5,
    availableCopies: 5,
    image: "https://covers.openlibrary.org/b/isbn/9780061120084-L.jpg",
    ebookUrl: "https://www.gutenberg.org/files/1342/1342-h/1342-h.htm",
    genre: "Classic"
  },
  {
    title: "1984",
    author: "George Orwell",
    isbn: "9780451524935",
    category: "fiction",
    description: "A dystopian novel set in a totalitarian society where independent thinking is a crime.",
    location: "Section A, Shelf 1",
    totalCopies: 4,
    availableCopies: 4,
    image: "https://covers.openlibrary.org/b/isbn/9780451524935-L.jpg",
    ebookUrl: "https://www.gutenberg.org/files/1984/1984-h/1984-h.htm",
    genre: "Dystopian"
  },
  {
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    isbn: "9780743273565",
    category: "fiction",
    description: "The story of the fabulously wealthy Jay Gatsby and his love for the beautiful Daisy Buchanan.",
    location: "Section A, Shelf 1",
    totalCopies: 3,
    availableCopies: 3,
    image: "https://covers.openlibrary.org/b/isbn/9780743273565-L.jpg",
    ebookUrl: "https://www.gutenberg.org/files/64317/64317-h/64317-h.htm",
    genre: "Classic"
  },
  {
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    isbn: "9780316769488",
    category: "fiction",
    description: "The story of Holden Caulfield, a teenage boy who struggles with alienation and loss of innocence.",
    location: "Section A, Shelf 1",
    totalCopies: 3,
    availableCopies: 3,
    image: "https://covers.openlibrary.org/b/isbn/9780316769488-L.jpg",
    ebookUrl: "https://www.gutenberg.org/ebooks/67426",
    genre: "Coming-of-age"
  },
  {
    title: "Pride and Prejudice",
    author: "Jane Austen",
    isbn: "9780141439518",
    category: "fiction",
    description: "A romantic novel that follows the emotional development of Elizabeth Bennet.",
    location: "Section A, Shelf 2",
    totalCopies: 4,
    availableCopies: 4,
    image: "https://covers.openlibrary.org/b/isbn/9780141439518-L.jpg",
    ebookUrl: "https://www.gutenberg.org/files/1342/1342-h/1342-h.htm",
    genre: "Romance"
  },
  {
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    isbn: "9780618260300",
    category: "fiction",
    description: "The adventure of Bilbo Baggins as he journeys to the Lonely Mountain with a group of dwarves.",
    location: "Section A, Shelf 2",
    totalCopies: 5,
    availableCopies: 5,
    image: "https://covers.openlibrary.org/b/isbn/9780618260300-L.jpg",
    ebookUrl: "https://www.gutenberg.org/ebooks/29728",
    genre: "Fantasy"
  },
  {
    title: "Brave New World",
    author: "Aldous Huxley",
    isbn: "9780060850524",
    category: "fiction",
    description: "A dystopian novel set in a futuristic World State of genetically modified citizens.",
    location: "Section A, Shelf 2",
    totalCopies: 3,
    availableCopies: 3,
    image: "https://covers.openlibrary.org/b/isbn/9780060850524-L.jpg",
    ebookUrl: "https://www.gutenberg.org/ebooks/63986",
    genre: "Dystopian"
  },
  {
    title: "The Lord of the Rings",
    author: "J.R.R. Tolkien",
    isbn: "9780618640157",
    category: "fiction",
    description: "Epic high-fantasy novel set in Middle-earth, following the quest to destroy the One Ring.",
    location: "Section A, Shelf 2",
    totalCopies: 5,
    availableCopies: 5,
    image: "https://covers.openlibrary.org/b/isbn/9780618640157-L.jpg",
    ebookUrl: "https://www.gutenberg.org/ebooks/61291",
    genre: "Fantasy"
  },
  {
    title: "Frankenstein",
    author: "Mary Shelley",
    isbn: "9780486282114",
    category: "fiction",
    description: "The story of Victor Frankenstein and the creature he brings to life in an unorthodox scientific experiment.",
    location: "Section A, Shelf 3",
    totalCopies: 3,
    availableCopies: 3,
    image: "https://covers.openlibrary.org/b/isbn/9780486282114-L.jpg",
    ebookUrl: "https://www.gutenberg.org/files/84/84-h/84-h.htm",
    genre: "Gothic"
  },
  {
    title: "The Alchemist",
    author: "Paulo Coelho",
    isbn: "9780062315007",
    category: "fiction",
    description: "The mystical story of Santiago, an Andalusian shepherd boy who yearns to travel in search of a worldly treasure.",
    location: "Section A, Shelf 3",
    totalCopies: 4,
    availableCopies: 4,
    image: "https://covers.openlibrary.org/b/isbn/9780062315007-L.jpg",
    ebookUrl: "https://www.gutenberg.org/ebooks/65989",
    genre: "Philosophical"
  },
  {
    title: "Crime and Punishment",
    author: "Fyodor Dostoevsky",
    isbn: "9780143058144",
    category: "fiction",
    description: "The story of Raskolnikov, an impoverished ex-student who formulates a plan to kill an unscrupulous pawnbroker.",
    location: "Section A, Shelf 3",
    totalCopies: 3,
    availableCopies: 3,
    image: "https://covers.openlibrary.org/b/isbn/9780143058144-L.jpg",
    ebookUrl: "https://www.gutenberg.org/files/2554/2554-h/2554-h.htm",
    genre: "Psychological"
  },
  {
    title: "Harry Potter and the Philosopher's Stone",
    author: "J.K. Rowling",
    isbn: "9780747532743",
    category: "fiction",
    description: "The first book in the Harry Potter series, following the life of a young wizard, Harry Potter.",
    location: "Section A, Shelf 3",
    totalCopies: 5,
    availableCopies: 5,
    image: "https://covers.openlibrary.org/b/isbn/9780747532743-L.jpg",
    ebookUrl: "https://www.gutenberg.org/ebooks/65990",
    genre: "Fantasy"
  },
  {
    title: "The Picture of Dorian Gray",
    author: "Oscar Wilde",
    isbn: "9780141439570",
    category: "fiction",
    description: "The story of a man who sells his soul for eternal youth and beauty.",
    location: "Section A, Shelf 4",
    totalCopies: 3,
    availableCopies: 3,
    image: "https://covers.openlibrary.org/b/isbn/9780141439570-L.jpg",
    ebookUrl: "https://www.gutenberg.org/files/174/174-h/174-h.htm",
    genre: "Gothic"
  },
  {
    title: "The Old Man and the Sea",
    author: "Ernest Hemingway",
    isbn: "9780684801223",
    category: "fiction",
    description: "The story of an aging Cuban fisherman who struggles with a giant marlin far out in the Gulf Stream.",
    location: "Section A, Shelf 4",
    totalCopies: 3,
    availableCopies: 3,
    image: "https://covers.openlibrary.org/b/isbn/9780684801223-L.jpg",
    ebookUrl: "https://www.gutenberg.org/ebooks/66151",
    genre: "Novella"
  },
  {
    title: "Moby-Dick",
    author: "Herman Melville",
    isbn: "9780142437247",
    category: "fiction",
    description: "The story of Captain Ahab's quest to avenge the whale that 'took' his leg.",
    location: "Section A, Shelf 4",
    totalCopies: 3,
    availableCopies: 3,
    image: "https://covers.openlibrary.org/b/isbn/9780142437247-L.jpg",
    ebookUrl: "https://www.gutenberg.org/files/2701/2701-h/2701-h.htm",
    genre: "Adventure"
  },
  {
    title: "Dracula",
    author: "Bram Stoker",
    isbn: "9780486411095",
    category: "fiction",
    description: "The novel tells the story of Dracula's attempt to move from Transylvania to England.",
    location: "Section A, Shelf 4",
    totalCopies: 3,
    availableCopies: 3,
    image: "https://covers.openlibrary.org/b/isbn/9780486411095-L.jpg",
    ebookUrl: "https://www.gutenberg.org/files/345/345-h/345-h.htm",
    genre: "Gothic"
  },
  {
    title: "The Odyssey",
    author: "Homer",
    isbn: "9780140268867",
    category: "fiction",
    description: "The epic poem follows the Greek hero Odysseus on his journey home after the fall of Troy.",
    location: "Section A, Shelf 5",
    totalCopies: 4,
    availableCopies: 4,
    image: "https://covers.openlibrary.org/b/isbn/9780140268867-L.jpg",
    ebookUrl: "https://www.gutenberg.org/files/1727/1727-h/1727-h.htm",
    genre: "Epic"
  },
  {
    title: "The Divine Comedy",
    author: "Dante Alighieri",
    isbn: "9780142437223",
    category: "fiction",
    description: "An epic poem that represents the journey of the soul toward God.",
    location: "Section A, Shelf 5",
    totalCopies: 3,
    availableCopies: 3,
    image: "https://covers.openlibrary.org/b/isbn/9780142437223-L.jpg",
    ebookUrl: "https://www.gutenberg.org/files/8800/8800-h/8800-h.htm",
    genre: "Epic"
  },
  {
    title: "The Count of Monte Cristo",
    author: "Alexandre Dumas",
    isbn: "9780140449266",
    category: "fiction",
    description: "The story of a man who is wrongfully imprisoned, escapes from jail, acquires a fortune, and sets about exacting revenge.",
    location: "Section A, Shelf 5",
    totalCopies: 3,
    availableCopies: 3,
    image: "https://covers.openlibrary.org/b/isbn/9780140449266-L.jpg",
    ebookUrl: "https://www.gutenberg.org/files/1184/1184-h/1184-h.htm",
    genre: "Adventure"
  },
  {
    title: "One Hundred Years of Solitude",
    author: "Gabriel García Márquez",
    isbn: "9780060883287",
    category: "fiction",
    description: "The multi-generational story of the Buendía family in the fictional town of Macondo.",
    location: "Section A, Shelf 5",
    totalCopies: 3,
    availableCopies: 3,
    image: "https://covers.openlibrary.org/b/isbn/9780060883287-L.jpg",
    ebookUrl: "https://www.gutenberg.org/ebooks/67294",
    genre: "Magical Realism"
  },
];

module.exports = libraryBooks;
