// Digital library catalog for CampusKart (IIT Patna).
// Every book has a real, working online-read link (ebookUrl).
// availableAtIITP flags whether a physical copy is on the IIT Patna shelves;
// books not physically available can still be read online via ebookUrl.

const books = [
  // ---------- FICTION (classics, public domain - Gutenberg) ----------
  {
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    isbn: "9780743273565",
    category: "fiction",
    description: "The story of the fabulously wealthy Jay Gatsby and his obsession with the beautiful Daisy Buchanan.",
    location: "Section A, Shelf 1",
    totalCopies: 5,
    availableCopies: 4,
    image: "https://covers.openlibrary.org/b/isbn/9780743273565-L.jpg",
    ebookUrl: "https://www.gutenberg.org/ebooks/64317",
    genre: "Classic",
    availableAtIITP: true,
  },
  {
    title: "Pride and Prejudice",
    author: "Jane Austen",
    isbn: "9780141439518",
    category: "fiction",
    description: "A witty romance following the spirited Elizabeth Bennet and the proud Mr. Darcy.",
    location: "Section A, Shelf 1",
    totalCopies: 4,
    availableCopies: 3,
    image: "https://covers.openlibrary.org/b/isbn/9780141439518-L.jpg",
    ebookUrl: "https://www.gutenberg.org/ebooks/1342",
    genre: "Romance",
    availableAtIITP: true,
  },
  {
    title: "Moby-Dick; or, The Whale",
    author: "Herman Melville",
    isbn: "9781503280786",
    category: "fiction",
    description: "Captain Ahab's monomaniacal quest to hunt the great white whale Moby Dick.",
    location: "Section A, Shelf 2",
    totalCopies: 3,
    availableCopies: 2,
    image: "https://covers.openlibrary.org/b/isbn/9781503280786-L.jpg",
    ebookUrl: "https://www.gutenberg.org/ebooks/2701",
    genre: "Adventure",
    availableAtIITP: true,
  },
  {
    title: "Frankenstein; or, The Modern Prometheus",
    author: "Mary Wollstonecraft Shelley",
    isbn: "9780486282114",
    category: "fiction",
    description: "Victor Frankenstein creates a sapient creature and unleashes tragic consequences.",
    location: "Section A, Shelf 2",
    totalCopies: 4,
    availableCopies: 0,
    image: "https://covers.openlibrary.org/b/isbn/9780486282114-L.jpg",
    ebookUrl: "https://www.gutenberg.org/ebooks/84",
    genre: "Gothic",
    availableAtIITP: false,
  },
  {
    title: "The Adventures of Sherlock Holmes",
    author: "Arthur Conan Doyle",
    isbn: "9781503275966",
    category: "fiction",
    description: "Twelve short stories featuring the brilliant detective Sherlock Holmes and Dr. Watson.",
    location: "Section A, Shelf 3",
    totalCopies: 5,
    availableCopies: 5,
    image: "https://covers.openlibrary.org/b/isbn/9781503275966-L.jpg",
    ebookUrl: "https://www.gutenberg.org/ebooks/1661",
    genre: "Mystery",
    availableAtIITP: true,
  },
  {
    title: "Crime and Punishment",
    author: "Fyodor Dostoevsky",
    isbn: "9780486415871",
    category: "fiction",
    description: "A poverty-stricken ex-student commits murder and wrestles with guilt and redemption.",
    location: "Section A, Shelf 3",
    totalCopies: 3,
    availableCopies: 1,
    image: "https://covers.openlibrary.org/b/isbn/9780486415871-L.jpg",
    ebookUrl: "https://www.gutenberg.org/ebooks/2554",
    genre: "Psychological",
    availableAtIITP: false,
  },
  {
    title: "War and Peace",
    author: "Leo Tolstoy",
    isbn: "9780199232765",
    category: "fiction",
    description: "An epic chronicle of Russian society during the Napoleonic era.",
    location: "Section A, Shelf 4",
    totalCopies: 2,
    availableCopies: 1,
    image: "https://covers.openlibrary.org/b/isbn/9780199232765-L.jpg",
    ebookUrl: "https://www.gutenberg.org/ebooks/2600",
    genre: "Historical Fiction",
    availableAtIITP: true,
  },
  {
    title: "The Picture of Dorian Gray",
    author: "Oscar Wilde",
    isbn: "9780141439570",
    category: "fiction",
    description: "A young man stays youthful while a portrait of him bears the marks of his corruption.",
    location: "Section A, Shelf 4",
    totalCopies: 3,
    availableCopies: 0,
    image: "https://covers.openlibrary.org/b/isbn/9780141439570-L.jpg",
    ebookUrl: "https://www.gutenberg.org/ebooks/174",
    genre: "Gothic",
    availableAtIITP: false,
  },
  {
    title: "Wuthering Heights",
    author: "Emily Bronte",
    isbn: "9780141439556",
    category: "fiction",
    description: "The turbulent and passionate tale of Heathcliff and Catherine on the Yorkshire moors.",
    location: "Section A, Shelf 5",
    totalCopies: 3,
    availableCopies: 2,
    image: "https://covers.openlibrary.org/b/isbn/9780141439556-L.jpg",
    ebookUrl: "https://www.gutenberg.org/ebooks/768",
    genre: "Gothic Romance",
    availableAtIITP: false,
  },
  {
    title: "Great Expectations",
    author: "Charles Dickens",
    isbn: "9780141439563",
    category: "fiction",
    description: "The orphan Pip's journey from a humble forge to gentlemanly ambitions in Victorian England.",
    location: "Section A, Shelf 5",
    totalCopies: 4,
    availableCopies: 3,
    image: "https://covers.openlibrary.org/b/isbn/9780141439563-L.jpg",
    ebookUrl: "https://www.gutenberg.org/ebooks/1400",
    genre: "Classic",
    availableAtIITP: true,
  },
  {
    title: "The Count of Monte Cristo",
    author: "Alexandre Dumas",
    isbn: "9780140449266",
    category: "fiction",
    description: "Wrongfully imprisoned Edmond Dantes escapes and exacts elaborate revenge on his betrayers.",
    location: "Section A, Shelf 6",
    totalCopies: 3,
    availableCopies: 3,
    image: "https://covers.openlibrary.org/b/isbn/9780140449266-L.jpg",
    ebookUrl: "https://www.gutenberg.org/ebooks/1184",
    genre: "Adventure",
    availableAtIITP: true,
  },
  {
    title: "Dracula",
    author: "Bram Stoker",
    isbn: "9780486411095",
    category: "fiction",
    description: "Count Dracula's attempt to spread the undead curse from Transylvania to England.",
    location: "Section A, Shelf 6",
    totalCopies: 4,
    availableCopies: 0,
    image: "https://covers.openlibrary.org/b/isbn/9780486411095-L.jpg",
    ebookUrl: "https://www.gutenberg.org/ebooks/345",
    genre: "Horror",
    availableAtIITP: false,
  },
  {
    title: "Alice's Adventures in Wonderland",
    author: "Lewis Carroll",
    isbn: "9780486275437",
    category: "fiction",
    description: "A young girl falls down a rabbit hole into a whimsical and nonsensical world.",
    location: "Section A, Shelf 7",
    totalCopies: 5,
    availableCopies: 4,
    image: "https://covers.openlibrary.org/b/isbn/9780486275437-L.jpg",
    ebookUrl: "https://www.gutenberg.org/ebooks/11",
    genre: "Fantasy",
    availableAtIITP: true,
  },
  {
    title: "The Adventures of Huckleberry Finn",
    author: "Mark Twain",
    isbn: "9780486280615",
    category: "fiction",
    description: "Huck Finn and the runaway slave Jim journey down the Mississippi River.",
    location: "Section A, Shelf 7",
    totalCopies: 3,
    availableCopies: 2,
    image: "https://covers.openlibrary.org/b/isbn/9780486280615-L.jpg",
    ebookUrl: "https://www.gutenberg.org/ebooks/76",
    genre: "Adventure",
    availableAtIITP: true,
  },
  {
    title: "Don Quixote",
    author: "Miguel de Cervantes",
    isbn: "9780142437230",
    category: "fiction",
    description: "An aging gentleman becomes a knight-errant and tilts at windmills across Spain.",
    location: "Section A, Shelf 8",
    totalCopies: 2,
    availableCopies: 1,
    image: "https://covers.openlibrary.org/b/isbn/9780142437230-L.jpg",
    ebookUrl: "https://www.gutenberg.org/ebooks/996",
    genre: "Classic",
    availableAtIITP: false,
  },

  // ---------- NON-FICTION ----------
  {
    title: "The Art of War",
    author: "Sun Tzu",
    isbn: "9781599869773",
    category: "non-fiction",
    description: "An ancient Chinese treatise on military strategy and tactics still studied today.",
    location: "Section B, Shelf 1",
    totalCopies: 4,
    availableCopies: 3,
    image: "https://covers.openlibrary.org/b/isbn/9781599869773-L.jpg",
    ebookUrl: "https://www.gutenberg.org/ebooks/132",
    genre: "Strategy",
    availableAtIITP: true,
  },
  {
    title: "The Wealth of Nations",
    author: "Adam Smith",
    isbn: "9780553585971",
    category: "non-fiction",
    description: "The foundational work of classical economics on markets, labour, and free trade.",
    location: "Section B, Shelf 1",
    totalCopies: 2,
    availableCopies: 1,
    image: "https://covers.openlibrary.org/b/isbn/9780553585971-L.jpg",
    ebookUrl: "https://www.gutenberg.org/ebooks/3300",
    genre: "Economics",
    availableAtIITP: true,
  },
  {
    title: "Walden",
    author: "Henry David Thoreau",
    isbn: "9780486284958",
    category: "non-fiction",
    description: "A reflection on simple living in natural surroundings at Walden Pond.",
    location: "Section B, Shelf 2",
    totalCopies: 3,
    availableCopies: 0,
    image: "https://covers.openlibrary.org/b/isbn/9780486284958-L.jpg",
    ebookUrl: "https://www.gutenberg.org/ebooks/205",
    genre: "Philosophy",
    availableAtIITP: false,
  },
  {
    title: "The Autobiography of Benjamin Franklin",
    author: "Benjamin Franklin",
    isbn: "9780486290737",
    category: "non-fiction",
    description: "Franklin's first-hand account of his rise from printer to founding statesman.",
    location: "Section B, Shelf 2",
    totalCopies: 3,
    availableCopies: 2,
    image: "https://covers.openlibrary.org/b/isbn/9780486290737-L.jpg",
    ebookUrl: "https://www.gutenberg.org/ebooks/20203",
    genre: "Memoir",
    availableAtIITP: false,
  },
  {
    title: "Meditations",
    author: "Marcus Aurelius",
    isbn: "9780486298238",
    category: "non-fiction",
    description: "The private Stoic reflections of a Roman emperor on virtue and self-discipline.",
    location: "Section B, Shelf 3",
    totalCopies: 4,
    availableCopies: 4,
    image: "https://covers.openlibrary.org/b/isbn/9780486298238-L.jpg",
    ebookUrl: "https://www.gutenberg.org/ebooks/2680",
    genre: "Philosophy",
    availableAtIITP: true,
  },
  {
    title: "How We Think",
    author: "John Dewey",
    isbn: "9781492373179",
    category: "non-fiction",
    description: "A classic exploration of reflective thinking and its role in education.",
    location: "Section B, Shelf 3",
    totalCopies: 2,
    availableCopies: 1,
    image: "https://covers.openlibrary.org/b/isbn/9781492373179-L.jpg",
    ebookUrl: "https://www.gutenberg.org/ebooks/37423",
    genre: "Education",
    availableAtIITP: false,
  },

  // ---------- SCIENCE ----------
  {
    title: "On the Origin of Species",
    author: "Charles Darwin",
    isbn: "9780451529060",
    category: "science",
    description: "Darwin's foundational work introducing the theory of evolution by natural selection.",
    location: "Section C, Shelf 1",
    totalCopies: 3,
    availableCopies: 2,
    image: "https://covers.openlibrary.org/b/isbn/9780451529060-L.jpg",
    ebookUrl: "https://www.gutenberg.org/ebooks/1228",
    genre: "Biology",
    availableAtIITP: true,
  },
  {
    title: "Relativity: The Special and General Theory",
    author: "Albert Einstein",
    isbn: "9780486417141",
    category: "science",
    description: "Einstein's own accessible explanation of his revolutionary theories of relativity.",
    location: "Section C, Shelf 1",
    totalCopies: 3,
    availableCopies: 3,
    image: "https://covers.openlibrary.org/b/isbn/9780486417141-L.jpg",
    ebookUrl: "https://www.gutenberg.org/ebooks/30155",
    genre: "Physics",
    availableAtIITP: true,
  },
  {
    title: "The Principia: Mathematical Principles of Natural Philosophy",
    author: "Isaac Newton",
    isbn: "9780520088177",
    category: "science",
    description: "Newton's landmark work establishing the laws of motion and universal gravitation.",
    location: "Section C, Shelf 2",
    totalCopies: 2,
    availableCopies: 1,
    image: "https://covers.openlibrary.org/b/isbn/9780520088177-L.jpg",
    ebookUrl: "https://www.gutenberg.org/ebooks/28233",
    genre: "Physics",
    availableAtIITP: true,
  },
  {
    title: "Experiments with Alternate Currents of High Potential",
    author: "Nikola Tesla",
    isbn: "9781605120508",
    category: "science",
    description: "Tesla's lectures on high-frequency, high-voltage alternating current phenomena.",
    location: "Section C, Shelf 2",
    totalCopies: 2,
    availableCopies: 0,
    image: "https://covers.openlibrary.org/b/isbn/9781605120508-L.jpg",
    ebookUrl: "https://www.gutenberg.org/ebooks/41999",
    genre: "Electrical Science",
    availableAtIITP: false,
  },
  {
    title: "The Chemical History of a Candle",
    author: "Michael Faraday",
    isbn: "9780486425429",
    category: "science",
    description: "Faraday's famous lectures using a candle to explain combustion and chemistry.",
    location: "Section C, Shelf 3",
    totalCopies: 3,
    availableCopies: 2,
    image: "https://covers.openlibrary.org/b/isbn/9780486425429-L.jpg",
    ebookUrl: "https://www.gutenberg.org/ebooks/14474",
    genre: "Chemistry",
    availableAtIITP: false,
  },
  {
    title: "A Brief History of Time",
    author: "Stephen Hawking",
    isbn: "9780553380163",
    category: "science",
    description: "An accessible account of cosmology, black holes, and the nature of the universe.",
    location: "Section C, Shelf 3",
    totalCopies: 4,
    availableCopies: 3,
    image: "https://covers.openlibrary.org/b/isbn/9780553380163-L.jpg",
    ebookUrl: "https://archive.org/details/briefhistoryofti0000hawk",
    genre: "Cosmology",
    availableAtIITP: true,
  },
  {
    title: "The Feynman Lectures on Physics, Vol. I",
    author: "Richard P. Feynman",
    isbn: "9780465024933",
    category: "science",
    description: "Feynman's celebrated introductory physics lectures on mechanics, radiation, and heat.",
    location: "Section C, Shelf 4",
    totalCopies: 3,
    availableCopies: 2,
    image: "https://covers.openlibrary.org/b/isbn/9780465024933-L.jpg",
    ebookUrl: "https://archive.org/details/feynman-lectures-on-physics-volume-1",
    genre: "Physics",
    availableAtIITP: true,
  },

  // ---------- HISTORY ----------
  {
    title: "The History of the Decline and Fall of the Roman Empire, Vol. 1",
    author: "Edward Gibbon",
    isbn: "9780140433937",
    category: "history",
    description: "Gibbon's monumental narrative of the collapse of the Roman Empire.",
    location: "Section D, Shelf 1",
    totalCopies: 2,
    availableCopies: 1,
    image: "https://covers.openlibrary.org/b/isbn/9780140433937-L.jpg",
    ebookUrl: "https://www.gutenberg.org/ebooks/731",
    genre: "Ancient History",
    availableAtIITP: false,
  },
  {
    title: "The Histories",
    author: "Herodotus",
    isbn: "9780140449082",
    category: "history",
    description: "The earliest surviving Greek prose history, recounting the Greco-Persian Wars.",
    location: "Section D, Shelf 1",
    totalCopies: 3,
    availableCopies: 2,
    image: "https://covers.openlibrary.org/b/isbn/9780140449082-L.jpg",
    ebookUrl: "https://www.gutenberg.org/ebooks/2707",
    genre: "Ancient History",
    availableAtIITP: true,
  },
  {
    title: "The History of the Peloponnesian War",
    author: "Thucydides",
    isbn: "9780140440393",
    category: "history",
    description: "A rigorous contemporary account of the war between Athens and Sparta.",
    location: "Section D, Shelf 2",
    totalCopies: 2,
    availableCopies: 0,
    image: "https://covers.openlibrary.org/b/isbn/9780140440393-L.jpg",
    ebookUrl: "https://www.gutenberg.org/ebooks/7142",
    genre: "Ancient History",
    availableAtIITP: false,
  },
  {
    title: "Discovery of India",
    author: "Jawaharlal Nehru",
    isbn: "9780143031031",
    category: "history",
    description: "Nehru's sweeping survey of Indian history, philosophy, and culture written from prison.",
    location: "Section D, Shelf 2",
    totalCopies: 4,
    availableCopies: 3,
    image: "https://covers.openlibrary.org/b/isbn/9780143031031-L.jpg",
    ebookUrl: "https://archive.org/details/discoveryofindia0000nehr",
    genre: "Indian History",
    availableAtIITP: true,
  },
  {
    title: "India After Gandhi",
    author: "Ramachandra Guha",
    isbn: "9780330505543",
    category: "history",
    description: "A comprehensive history of the world's largest democracy since independence.",
    location: "Section D, Shelf 3",
    totalCopies: 3,
    availableCopies: 2,
    image: "https://covers.openlibrary.org/b/isbn/9780330505543-L.jpg",
    ebookUrl: "https://archive.org/details/indiaaftergandhi0000guha",
    genre: "Indian History",
    availableAtIITP: true,
  },
  {
    title: "The Story of My Experiments with Truth",
    author: "Mohandas K. Gandhi",
    isbn: "9780486245935",
    category: "history",
    description: "Gandhi's autobiography tracing his moral and political development.",
    location: "Section D, Shelf 3",
    totalCopies: 4,
    availableCopies: 0,
    image: "https://covers.openlibrary.org/b/isbn/9780486245935-L.jpg",
    ebookUrl: "https://www.gutenberg.org/ebooks/56098",
    genre: "Indian History",
    availableAtIITP: false,
  },

  // ---------- BIOGRAPHY ----------
  {
    title: "The Life of Samuel Johnson",
    author: "James Boswell",
    isbn: "9780140436624",
    category: "biography",
    description: "Boswell's celebrated and intimate biography of the writer Samuel Johnson.",
    location: "Section E, Shelf 1",
    totalCopies: 2,
    availableCopies: 1,
    image: "https://covers.openlibrary.org/b/isbn/9780140436624-L.jpg",
    ebookUrl: "https://www.gutenberg.org/ebooks/1564",
    genre: "Literary Biography",
    availableAtIITP: false,
  },
  {
    title: "The Souls of Black Folk",
    author: "W. E. B. Du Bois",
    isbn: "9780486280417",
    category: "biography",
    description: "A landmark collection of autobiographical and sociological essays on Black life in America.",
    location: "Section E, Shelf 1",
    totalCopies: 3,
    availableCopies: 2,
    image: "https://covers.openlibrary.org/b/isbn/9780486280417-L.jpg",
    ebookUrl: "https://www.gutenberg.org/ebooks/408",
    genre: "Autobiography",
    availableAtIITP: true,
  },
  {
    title: "Narrative of the Life of Frederick Douglass",
    author: "Frederick Douglass",
    isbn: "9780486284996",
    category: "biography",
    description: "Douglass's powerful first-hand account of his life as a slave and his escape to freedom.",
    location: "Section E, Shelf 2",
    totalCopies: 4,
    availableCopies: 3,
    image: "https://covers.openlibrary.org/b/isbn/9780486284996-L.jpg",
    ebookUrl: "https://www.gutenberg.org/ebooks/23",
    genre: "Memoir",
    availableAtIITP: true,
  },
  {
    title: "The Diary of a Young Girl",
    author: "Anne Frank",
    isbn: "9780553296983",
    category: "biography",
    description: "The wartime diary of a Jewish girl hiding from the Nazis in Amsterdam.",
    location: "Section E, Shelf 2",
    totalCopies: 5,
    availableCopies: 4,
    image: "https://covers.openlibrary.org/b/isbn/9780553296983-L.jpg",
    ebookUrl: "https://archive.org/details/diaryofyounggirl0000fran",
    genre: "Memoir",
    availableAtIITP: true,
  },
  {
    title: "Wings of Fire: An Autobiography",
    author: "A. P. J. Abdul Kalam",
    isbn: "9788173711466",
    category: "biography",
    description: "The autobiography of India's missile man and former president, A. P. J. Abdul Kalam.",
    location: "Section E, Shelf 3",
    totalCopies: 5,
    availableCopies: 0,
    image: "https://covers.openlibrary.org/b/isbn/9788173711466-L.jpg",
    ebookUrl: "https://archive.org/details/wingsoffireautob0000kala",
    genre: "Indian Biography",
    availableAtIITP: false,
  },
  {
    title: "The Autobiography of Charles Darwin",
    author: "Charles Darwin",
    isbn: "9780393310696",
    category: "biography",
    description: "Darwin's reflections on his life, work, and the development of his scientific ideas.",
    location: "Section E, Shelf 3",
    totalCopies: 2,
    availableCopies: 1,
    image: "https://covers.openlibrary.org/b/isbn/9780393310696-L.jpg",
    ebookUrl: "https://www.gutenberg.org/ebooks/2010",
    genre: "Science Biography",
    availableAtIITP: false,
  },

  // ---------- TECHNOLOGY (CS / engineering) ----------
  {
    title: "Introduction to Algorithms",
    author: "Thomas H. Cormen, Charles E. Leiserson, Ronald L. Rivest, Clifford Stein",
    isbn: "9780262033848",
    category: "technology",
    description: "The definitive comprehensive reference on algorithms, known as CLRS.",
    location: "Section F, Shelf 1",
    totalCopies: 6,
    availableCopies: 5,
    image: "https://covers.openlibrary.org/b/isbn/9780262033848-L.jpg",
    ebookUrl: "https://archive.org/details/introduction-to-algorithms-third-edition",
    genre: "Computer Science",
    availableAtIITP: true,
  },
  {
    title: "Computer Networks",
    author: "Andrew S. Tanenbaum, David J. Wetherall",
    isbn: "9780132126953",
    category: "technology",
    description: "Tanenbaum's classic textbook covering the principles and practice of computer networking.",
    location: "Section F, Shelf 1",
    totalCopies: 5,
    availableCopies: 3,
    image: "https://covers.openlibrary.org/b/isbn/9780132126953-L.jpg",
    ebookUrl: "https://archive.org/details/computernetworks0005tane",
    genre: "Networking",
    availableAtIITP: true,
  },
  {
    title: "Modern Operating Systems",
    author: "Andrew S. Tanenbaum, Herbert Bos",
    isbn: "9780133591620",
    category: "technology",
    description: "A thorough treatment of operating system concepts, processes, memory, and file systems.",
    location: "Section F, Shelf 2",
    totalCopies: 4,
    availableCopies: 0,
    image: "https://covers.openlibrary.org/b/isbn/9780133591620-L.jpg",
    ebookUrl: "https://archive.org/details/modernoperatings0000tane",
    genre: "Operating Systems",
    availableAtIITP: false,
  },
  {
    title: "Algorithms",
    author: "Robert Sedgewick, Kevin Wayne",
    isbn: "9780321573513",
    category: "technology",
    description: "Sedgewick's modern survey of essential algorithms and data structures with Java.",
    location: "Section F, Shelf 2",
    totalCopies: 4,
    availableCopies: 3,
    image: "https://covers.openlibrary.org/b/isbn/9780321573513-L.jpg",
    ebookUrl: "https://archive.org/details/algorithms0000sedg",
    genre: "Computer Science",
    availableAtIITP: true,
  },
  {
    title: "The C Programming Language",
    author: "Brian W. Kernighan, Dennis M. Ritchie",
    isbn: "9780131103627",
    category: "technology",
    description: "The classic, authoritative introduction to the C language by its creators.",
    location: "Section F, Shelf 3",
    totalCopies: 5,
    availableCopies: 4,
    image: "https://covers.openlibrary.org/b/isbn/9780131103627-L.jpg",
    ebookUrl: "https://archive.org/details/cprogramminglang0000kern",
    genre: "Programming",
    availableAtIITP: true,
  },
  {
    title: "Structure and Interpretation of Computer Programs",
    author: "Harold Abelson, Gerald Jay Sussman, Julie Sussman",
    isbn: "9780262510875",
    category: "technology",
    description: "The influential MIT text on programming abstraction, recursion, and interpretation.",
    location: "Section F, Shelf 3",
    totalCopies: 3,
    availableCopies: 2,
    image: "https://covers.openlibrary.org/b/isbn/9780262510875-L.jpg",
    ebookUrl: "https://archive.org/details/structureinterpr00abel",
    genre: "Programming",
    availableAtIITP: true,
  },
  {
    title: "Compilers: Principles, Techniques, and Tools",
    author: "Alfred V. Aho, Monica S. Lam, Ravi Sethi, Jeffrey D. Ullman",
    isbn: "9780321486813",
    category: "technology",
    description: "The Dragon Book, the standard reference on compiler design and construction.",
    location: "Section F, Shelf 4",
    totalCopies: 3,
    availableCopies: 0,
    image: "https://covers.openlibrary.org/b/isbn/9780321486813-L.jpg",
    ebookUrl: "https://archive.org/details/compilersprincip0000ahoa",
    genre: "Compilers",
    availableAtIITP: false,
  },
  {
    title: "Artificial Intelligence: A Modern Approach",
    author: "Stuart Russell, Peter Norvig",
    isbn: "9780136042594",
    category: "technology",
    description: "The leading textbook on artificial intelligence, covering search, learning, and reasoning.",
    location: "Section F, Shelf 4",
    totalCopies: 4,
    availableCopies: 3,
    image: "https://covers.openlibrary.org/b/isbn/9780136042594-L.jpg",
    ebookUrl: "https://archive.org/details/artificialintell0000russ",
    genre: "Artificial Intelligence",
    availableAtIITP: true,
  },
  {
    title: "The Pragmatic Programmer",
    author: "Andrew Hunt, David Thomas",
    isbn: "9780201616224",
    category: "technology",
    description: "Practical advice and timeless principles for software craftsmanship.",
    location: "Section F, Shelf 5",
    totalCopies: 4,
    availableCopies: 2,
    image: "https://covers.openlibrary.org/b/isbn/9780201616224-L.jpg",
    ebookUrl: "https://archive.org/details/pragmaticprogram0000hunt",
    genre: "Software Engineering",
    availableAtIITP: false,
  },
  {
    title: "Database System Concepts",
    author: "Abraham Silberschatz, Henry F. Korth, S. Sudarshan",
    isbn: "9780073523323",
    category: "technology",
    description: "A comprehensive introduction to the design and implementation of database systems.",
    location: "Section F, Shelf 5",
    totalCopies: 4,
    availableCopies: 3,
    image: "https://covers.openlibrary.org/b/isbn/9780073523323-L.jpg",
    ebookUrl: "https://archive.org/details/databasesystemco0000silb",
    genre: "Databases",
    availableAtIITP: true,
  },

  // ---------- ART ----------
  {
    title: "Lives of the Most Excellent Painters, Sculptors, and Architects",
    author: "Giorgio Vasari",
    isbn: "9780199537198",
    category: "art",
    description: "The seminal Renaissance collection of artist biographies by Giorgio Vasari.",
    location: "Section G, Shelf 1",
    totalCopies: 2,
    availableCopies: 1,
    image: "https://covers.openlibrary.org/b/isbn/9780199537198-L.jpg",
    ebookUrl: "https://www.gutenberg.org/ebooks/25326",
    genre: "Art History",
    availableAtIITP: true,
  },
  {
    title: "Concerning the Spiritual in Art",
    author: "Wassily Kandinsky",
    isbn: "9780486234113",
    category: "art",
    description: "Kandinsky's influential treatise on abstraction and the spiritual basis of art.",
    location: "Section G, Shelf 1",
    totalCopies: 3,
    availableCopies: 0,
    image: "https://covers.openlibrary.org/b/isbn/9780486234113-L.jpg",
    ebookUrl: "https://www.gutenberg.org/ebooks/5321",
    genre: "Art Theory",
    availableAtIITP: false,
  },
  {
    title: "The Notebooks of Leonardo da Vinci",
    author: "Leonardo da Vinci",
    isbn: "9780486225722",
    category: "art",
    description: "Leonardo's notes and sketches on painting, anatomy, engineering, and nature.",
    location: "Section G, Shelf 2",
    totalCopies: 2,
    availableCopies: 2,
    image: "https://covers.openlibrary.org/b/isbn/9780486225722-L.jpg",
    ebookUrl: "https://www.gutenberg.org/ebooks/5000",
    genre: "Art & Science",
    availableAtIITP: true,
  },
  {
    title: "The Theory and Practice of Perspective",
    author: "George Adolphus Storey",
    isbn: "9781013772573",
    category: "art",
    description: "A practical Victorian manual on the principles of linear perspective for artists.",
    location: "Section G, Shelf 2",
    totalCopies: 2,
    availableCopies: 1,
    image: "https://covers.openlibrary.org/b/isbn/9781013772573-L.jpg",
    ebookUrl: "https://www.gutenberg.org/ebooks/26000",
    genre: "Drawing",
    availableAtIITP: false,
  },

  // ---------- ACADEMIC (math / textbooks / scholarly) ----------
  {
    title: "Calculus, Vol. 1",
    author: "Tom M. Apostol",
    isbn: "9780471000051",
    category: "academic",
    description: "A rigorous one-variable calculus textbook with linear algebra, widely used in IITs.",
    location: "Section H, Shelf 1",
    totalCopies: 5,
    availableCopies: 4,
    image: "https://covers.openlibrary.org/b/isbn/9780471000051-L.jpg",
    ebookUrl: "https://archive.org/details/calculus0001apos",
    genre: "Mathematics",
    availableAtIITP: true,
  },
  {
    title: "Linear Algebra and Its Applications",
    author: "Gilbert Strang",
    isbn: "9780030105678",
    category: "academic",
    description: "Strang's classic treatment of linear algebra emphasizing applications and intuition.",
    location: "Section H, Shelf 1",
    totalCopies: 4,
    availableCopies: 3,
    image: "https://covers.openlibrary.org/b/isbn/9780030105678-L.jpg",
    ebookUrl: "https://archive.org/details/linearalgebraits0000stra",
    genre: "Mathematics",
    availableAtIITP: true,
  },
  {
    title: "Principles of Mathematical Analysis",
    author: "Walter Rudin",
    isbn: "9780070542358",
    category: "academic",
    description: "Rudin's rigorous introduction to real and complex analysis, known as Baby Rudin.",
    location: "Section H, Shelf 2",
    totalCopies: 3,
    availableCopies: 0,
    image: "https://covers.openlibrary.org/b/isbn/9780070542358-L.jpg",
    ebookUrl: "https://archive.org/details/principlesofmath0000rudi",
    genre: "Mathematics",
    availableAtIITP: false,
  },
  {
    title: "The Elements of Euclid",
    author: "Euclid",
    isbn: "9780486600888",
    category: "academic",
    description: "The foundational Greek treatise on geometry and number theory.",
    location: "Section H, Shelf 2",
    totalCopies: 3,
    availableCopies: 2,
    image: "https://covers.openlibrary.org/b/isbn/9780486600888-L.jpg",
    ebookUrl: "https://www.gutenberg.org/ebooks/21076",
    genre: "Mathematics",
    availableAtIITP: true,
  },
  {
    title: "Introduction to Probability",
    author: "Dimitri P. Bertsekas, John N. Tsitsiklis",
    isbn: "9781886529236",
    category: "academic",
    description: "A clear introduction to probability theory used in many engineering curricula.",
    location: "Section H, Shelf 3",
    totalCopies: 4,
    availableCopies: 3,
    image: "https://covers.openlibrary.org/b/isbn/9781886529236-L.jpg",
    ebookUrl: "https://archive.org/details/introductiontopr0000bert",
    genre: "Statistics",
    availableAtIITP: true,
  },
  {
    title: "A Treatise on Electricity and Magnetism, Vol. 1",
    author: "James Clerk Maxwell",
    isbn: "9781108014038",
    category: "academic",
    description: "Maxwell's foundational scholarly treatise unifying electricity and magnetism.",
    location: "Section H, Shelf 3",
    totalCopies: 2,
    availableCopies: 1,
    image: "https://covers.openlibrary.org/b/isbn/9781108014038-L.jpg",
    ebookUrl: "https://archive.org/details/electricandmagne01maxw",
    genre: "Physics",
    availableAtIITP: false,
  },
  {
    title: "Engineering Mechanics: Dynamics",
    author: "J. L. Meriam, L. G. Kraige",
    isbn: "9780470614815",
    category: "academic",
    description: "A widely adopted undergraduate textbook on the dynamics of rigid bodies.",
    location: "Section H, Shelf 4",
    totalCopies: 4,
    availableCopies: 0,
    image: "https://covers.openlibrary.org/b/isbn/9780470614815-L.jpg",
    ebookUrl: "https://archive.org/details/engineeringmecha0000meri",
    genre: "Mechanical Engineering",
    availableAtIITP: false,
  },

  // ---------- REFERENCE ----------
  {
    title: "Webster's Unabridged Dictionary",
    author: "Noah Webster",
    isbn: "9781892209030",
    category: "reference",
    description: "A comprehensive English dictionary, a standard reference for definitions and usage.",
    location: "Section I, Shelf 1",
    totalCopies: 2,
    availableCopies: 2,
    image: "https://covers.openlibrary.org/b/isbn/9781892209030-L.jpg",
    ebookUrl: "https://www.gutenberg.org/ebooks/29765",
    genre: "Dictionary",
    availableAtIITP: true,
  },
  {
    title: "Roget's Thesaurus of English Words and Phrases",
    author: "Peter Mark Roget",
    isbn: "9780062843739",
    category: "reference",
    description: "The classic thesaurus organizing words by the ideas they express.",
    location: "Section I, Shelf 1",
    totalCopies: 3,
    availableCopies: 2,
    image: "https://covers.openlibrary.org/b/isbn/9780062843739-L.jpg",
    ebookUrl: "https://www.gutenberg.org/ebooks/10681",
    genre: "Thesaurus",
    availableAtIITP: true,
  },
  {
    title: "The World Factbook",
    author: "Central Intelligence Agency",
    isbn: "9781510758636",
    category: "reference",
    description: "An annual reference of country profiles covering geography, economy, and demographics.",
    location: "Section I, Shelf 2",
    totalCopies: 2,
    availableCopies: 0,
    image: "https://covers.openlibrary.org/b/isbn/9781510758636-L.jpg",
    ebookUrl: "https://www.gutenberg.org/ebooks/35830",
    genre: "Almanac",
    availableAtIITP: false,
  },
  {
    title: "CRC Standard Mathematical Tables and Formulae",
    author: "Daniel Zwillinger",
    isbn: "9781439835487",
    category: "reference",
    description: "An indispensable reference of mathematical tables, formulae, and constants.",
    location: "Section I, Shelf 2",
    totalCopies: 3,
    availableCopies: 2,
    image: "https://covers.openlibrary.org/b/isbn/9781439835487-L.jpg",
    ebookUrl: "https://archive.org/details/crcstandardmathe0000zwil",
    genre: "Handbook",
    availableAtIITP: true,
  },
  {
    title: "Bartlett's Familiar Quotations",
    author: "John Bartlett",
    isbn: "9780316084604",
    category: "reference",
    description: "A celebrated collection of memorable quotations from literature and history.",
    location: "Section I, Shelf 3",
    totalCopies: 2,
    availableCopies: 1,
    image: "https://covers.openlibrary.org/b/isbn/9780316084604-L.jpg",
    ebookUrl: "https://www.gutenberg.org/ebooks/56808",
    genre: "Quotations",
    availableAtIITP: false,
  },

  // ---------- PERIODICAL ----------
  {
    title: "Scientific American (Archive Collection)",
    author: "Scientific American",
    isbn: "9780000000017",
    category: "periodical",
    description: "Archived issues of the long-running popular science magazine Scientific American.",
    location: "Section J, Shelf 1",
    totalCopies: 3,
    availableCopies: 2,
    image: "https://covers.openlibrary.org/b/isbn/9780000000017-L.jpg",
    ebookUrl: "https://archive.org/details/scientific-american-1845",
    genre: "Science Magazine",
    availableAtIITP: true,
  },
  {
    title: "Nature (Journal Archive)",
    author: "Nature Publishing Group",
    isbn: "9780000000024",
    category: "periodical",
    description: "Archived volumes of Nature, the international weekly journal of science.",
    location: "Section J, Shelf 1",
    totalCopies: 2,
    availableCopies: 1,
    image: "https://covers.openlibrary.org/b/isbn/9780000000024-L.jpg",
    ebookUrl: "https://archive.org/details/nature01unse",
    genre: "Science Journal",
    availableAtIITP: false,
  },
  {
    title: "The Strand Magazine (1891 Archive)",
    author: "George Newnes",
    isbn: "9780000000031",
    category: "periodical",
    description: "The illustrated monthly magazine that first serialized Sherlock Holmes stories.",
    location: "Section J, Shelf 2",
    totalCopies: 2,
    availableCopies: 2,
    image: "https://covers.openlibrary.org/b/isbn/9780000000031-L.jpg",
    ebookUrl: "https://archive.org/details/TheStrandMagazineAnIllustratedMonthly",
    genre: "Literary Magazine",
    availableAtIITP: true,
  },
  {
    title: "Popular Science Monthly, Volume 1",
    author: "Popular Science",
    isbn: "9780000000048",
    category: "periodical",
    description: "The inaugural volume of Popular Science Monthly covering 19th-century science.",
    location: "Section J, Shelf 2",
    totalCopies: 2,
    availableCopies: 0,
    image: "https://covers.openlibrary.org/b/isbn/9780000000048-L.jpg",
    ebookUrl: "https://www.gutenberg.org/ebooks/15832",
    genre: "Science Magazine",
    availableAtIITP: false,
  },
  {
    title: "The Atlantic Monthly, Volume 1 (1857)",
    author: "The Atlantic",
    isbn: "9780000000055",
    category: "periodical",
    description: "The first volume of the literary and cultural magazine The Atlantic Monthly.",
    location: "Section J, Shelf 3",
    totalCopies: 2,
    availableCopies: 1,
    image: "https://covers.openlibrary.org/b/isbn/9780000000055-L.jpg",
    ebookUrl: "https://www.gutenberg.org/ebooks/12241",
    genre: "Literary Magazine",
    availableAtIITP: true,
  },
];

module.exports = books;
