// Library Books Non-Fiction Seed Data
const libraryBooksNonFiction = [
  // Non-Fiction Books (16 books)
  {
    title: "Sapiens: A Brief History of Humankind",
    author: "Yuval Noah Harari",
    isbn: "9780062316097",
    category: "non-fiction",
    description: "A survey of the history of humankind from the evolution of Homo sapiens to the present day.",
    location: "Section B, Shelf 1",
    totalCopies: 4,
    availableCopies: 4,
    image: "https://covers.openlibrary.org/b/isbn/9780062316097-L.jpg",
    ebookUrl: "https://www.gutenberg.org/ebooks/45175",
    genre: "Anthropology"
  },
  {
    title: "Thinking, Fast and Slow",
    author: "Daniel Kahneman",
    isbn: "9780374533557",
    category: "non-fiction",
    description: "The book summarizes research that Kahneman performed over decades, often in collaboration with Amos Tversky.",
    location: "Section B, Shelf 1",
    totalCopies: 3,
    availableCopies: 3,
    image: "https://covers.openlibrary.org/b/isbn/9780374533557-L.jpg",
    ebookUrl: "https://www.gutenberg.org/ebooks/58025",
    genre: "Psychology"
  },
  {
    title: "A Brief History of Time",
    author: "Stephen Hawking",
    isbn: "9780553380163",
    category: "non-fiction",
    description: "A book on theoretical cosmology that attempts to explain a range of subjects in cosmology.",
    location: "Section B, Shelf 1",
    totalCopies: 4,
    availableCopies: 4,
    image: "https://covers.openlibrary.org/b/isbn/9780553380163-L.jpg",
    ebookUrl: "https://www.gutenberg.org/ebooks/60727",
    genre: "Cosmology"
  },
  {
    title: "The Diary of a Young Girl",
    author: "Anne Frank",
    isbn: "9780553577129",
    category: "non-fiction",
    description: "The writings from the Dutch-language diary kept by Anne Frank while she was in hiding for two years.",
    location: "Section B, Shelf 1",
    totalCopies: 4,
    availableCopies: 4,
    image: "https://covers.openlibrary.org/b/isbn/9780553577129-L.jpg",
    ebookUrl: "https://www.gutenberg.org/ebooks/66774",
    genre: "Memoir"
  },
  {
    title: "Man's Search for Meaning",
    author: "Viktor E. Frankl",
    isbn: "9780807014295",
    category: "non-fiction",
    description: "A book by psychologist Viktor Frankl chronicling his experiences as a prisoner in Nazi concentration camps.",
    location: "Section B, Shelf 2",
    totalCopies: 3,
    availableCopies: 3,
    image: "https://covers.openlibrary.org/b/isbn/9780807014295-L.jpg",
    ebookUrl: "https://www.gutenberg.org/ebooks/65772",
    genre: "Psychology"
  },
  {
    title: "In Cold Blood",
    author: "Truman Capote",
    isbn: "9780679745587",
    category: "non-fiction",
    description: "The book details the 1959 murders of four members of the Herbert Clutter family in the small farming community of Holcomb, Kansas.",
    location: "Section B, Shelf 2",
    totalCopies: 3,
    availableCopies: 3,
    image: "https://covers.openlibrary.org/b/isbn/9780679745587-L.jpg",
    ebookUrl: "https://www.gutenberg.org/ebooks/62746",
    genre: "True Crime"
  },
  {
    title: "The Elements of Style",
    author: "William Strunk Jr. & E.B. White",
    isbn: "9780205309023",
    category: "non-fiction",
    description: "A prescriptive American English writing style guide focusing on grammar, punctuation, and style.",
    location: "Section B, Shelf 2",
    totalCopies: 5,
    availableCopies: 5,
    image: "https://covers.openlibrary.org/b/isbn/9780205309023-L.jpg",
    ebookUrl: "https://www.gutenberg.org/files/37134/37134-h/37134-h.htm",
    genre: "Writing"
  },
  {
    title: "The Power of Habit",
    author: "Charles Duhigg",
    isbn: "9780812981605",
    category: "non-fiction",
    description: "An award-winning business reporter explores why habits exist and how they can be changed.",
    location: "Section B, Shelf 2",
    totalCopies: 4,
    availableCopies: 4,
    image: "https://covers.openlibrary.org/b/isbn/9780812981605-L.jpg",
    ebookUrl: "https://www.gutenberg.org/ebooks/62878",
    genre: "Self-Help"
  },
  {
    title: "Educated",
    author: "Tara Westover",
    isbn: "9780399590504",
    category: "non-fiction",
    description: "A memoir about a woman who kept out of school, leaves her survivalist family and goes on to earn a PhD from Cambridge University.",
    location: "Section B, Shelf 3",
    totalCopies: 3,
    availableCopies: 3,
    image: "https://covers.openlibrary.org/b/isbn/9780399590504-L.jpg",
    ebookUrl: "https://www.gutenberg.org/ebooks/60824",
    genre: "Memoir"
  },
  {
    title: "The Immortal Life of Henrietta Lacks",
    author: "Rebecca Skloot",
    isbn: "9781400052189",
    category: "non-fiction",
    description: "The story of Henrietta Lacks and the immortal cell line, known as HeLa, that came from her cervical cancer cells in 1951.",
    location: "Section B, Shelf 3",
    totalCopies: 3,
    availableCopies: 3,
    image: "https://covers.openlibrary.org/b/isbn/9781400052189-L.jpg",
    ebookUrl: "https://www.gutenberg.org/ebooks/66123",
    genre: "Biography"
  },
  {
    title: "Becoming",
    author: "Michelle Obama",
    isbn: "9781524763138",
    category: "non-fiction",
    description: "A memoir by former United States first lady Michelle Obama.",
    location: "Section B, Shelf 3",
    totalCopies: 4,
    availableCopies: 4,
    image: "https://covers.openlibrary.org/b/isbn/9781524763138-L.jpg",
    ebookUrl: "https://www.gutenberg.org/ebooks/65982",
    genre: "Memoir"
  },
  {
    title: "The Feynman Lectures on Physics",
    author: "Richard P. Feynman",
    isbn: "9780465023829",
    category: "non-fiction",
    description: "A physics textbook based on lectures by Richard Feynman for undergraduate students at Caltech.",
    location: "Section B, Shelf 3",
    totalCopies: 3,
    availableCopies: 3,
    image: "https://covers.openlibrary.org/b/isbn/9780465023829-L.jpg",
    ebookUrl: "https://www.gutenberg.org/ebooks/62871",
    genre: "Physics"
  },
  {
    title: "Freakonomics",
    author: "Steven D. Levitt & Stephen J. Dubner",
    isbn: "9780061234002",
    category: "non-fiction",
    description: "A book that explores the hidden side of everything by examining how incentives work and how people get what they want.",
    location: "Section B, Shelf 4",
    totalCopies: 4,
    availableCopies: 4,
    image: "https://covers.openlibrary.org/b/isbn/9780061234002-L.jpg",
    ebookUrl: "https://www.gutenberg.org/ebooks/63985",
    genre: "Economics"
  },
  {
    title: "The Art of War",
    author: "Sun Tzu",
    isbn: "9780143037521",
    category: "non-fiction",
    description: "An ancient Chinese military treatise dating from the 5th century BC.",
    location: "Section B, Shelf 4",
    totalCopies: 5,
    availableCopies: 5,
    image: "https://covers.openlibrary.org/b/isbn/9780143037521-L.jpg",
    ebookUrl: "https://www.gutenberg.org/files/132/132-h/132-h.htm",
    genre: "Military Strategy"
  },
  {
    title: "Silent Spring",
    author: "Rachel Carson",
    isbn: "9780618249060",
    category: "non-fiction",
    description: "A book that documented the adverse environmental effects caused by the indiscriminate use of pesticides.",
    location: "Section B, Shelf 4",
    totalCopies: 3,
    availableCopies: 3,
    image: "https://covers.openlibrary.org/b/isbn/9780618249060-L.jpg",
    ebookUrl: "https://www.gutenberg.org/ebooks/61305",
    genre: "Environmental Science"
  },
  {
    title: "Atomic Habits",
    author: "James Clear",
    isbn: "9780735211292",
    category: "non-fiction",
    description: "A practical guide to breaking bad habits and building good ones.",
    location: "Section B, Shelf 4",
    totalCopies: 4,
    availableCopies: 4,
    image: "https://covers.openlibrary.org/b/isbn/9780735211292-L.jpg",
    ebookUrl: "https://www.gutenberg.org/ebooks/65987",
    genre: "Self-Help"
  },
];

module.exports = libraryBooksNonFiction;
